### ISSUE TITLE
Inconsistent table row height with items other than text

### ISSUE THREAD

**Issue by alexlya** [codidact/co-design#11]
Inserting buttons into table increases table's row height. Screenshot should be self-explanatory: 

![image](https://user-images.githubusercontent.com/23587065/72280127-8458db00-362f-11ea-9e16-0fc741694740.png)
It's not a big deal but it would be nice for row height not to change.

**Comment by luap42** [comment]
I'll look into it, but I'm not sure, whether it is feasible.

Buttons have a different height than "normal" text. That's something that can't be changed. It might work to remove the padding of the table cell, when the only child is a button, but I am not sure, whether that is okay.

**Comment by ArtOfCode-** [comment]
I would call this status-bydesign: table rows _should_ expand when their contents do, just as they would for multiple lines of text.

**Comment by luap42** [comment]
I am formally declining this issue, for these reasons:

The behavior is definitely not a bug. As @ArtOfCode- and I said before, it is pretty much by design, that table rows expand to the size their content needs.

The issue might also be considered as feature request, though. However, I think, that it is not worth implementing, for these reasons:

It might be possible to design for these special-cases, but I don't think this is something we should do. In the end, most tables will have a common structure between their rows, so that there won't be a difference within one table. As we can see from the screenshot, the other cells are centered, so that is no problem, either.
