### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by appgurueu** [codidact/co-design#12]
There are hardcoded values scattered all around the code, which might pose issues later regarding responsiveness. Examples:

Hardcoded sizes (of a shadow in this case) in pixels, `rem` or the like should rather be used: https://github.com/codidact/co-design/blob/develop/src/_modals.scss#L22

> Absolute length units are not recommended for use on screen

See [W3Schools](https://www.w3schools.com/cssref/css_units.asp) for details.

Hardcoded ratio (of a modal body, which can only have 2/3 of the modal's width, which will lead to trouble on mobile devices): https://github.com/codidact/co-design/blob/develop/src/_modals.scss#L62

**Comment by luap42** [comment]
I'll review this later/tomorrow and fix some of these things.

However, at least the last point is not a problem:

1. If the modal body exceeds that height, scroll bars appear.
2. On mobile, the modal body spans the whole height, due to this rule: https://github.com/codidact/co-design/blob/c969990dc246e4db361356b8ca86d14540854d34/src/_modals.scss#L115

**Comment by luap42** [comment]
I don't think, the hard-coded values will lead to a problem with responsiveness. CD is fully responsive AFAIK and AFAICT.

I'll review the decision to use pixels rather than ems, however that might take some time and is rather low priority (at least for me - feel free to open a PR) unless one can demonstrate actual problems with it (with screenshots).

**Comment by appgurueu** [comment]
Hardcoded values might pose issues regarding code quality.

I should've probably opened a separate issue; it's about the pixels. Pixels and other absolute units are *per definition* non-responsive. Which means a user on a 4k display will have the same button shadow as somebody on his 640p Raspi display. And that's non-responsive.

**Comment by luap42** [comment]
This is being worked on.

**Comment by luap42** [comment]
All values are now set in the `_config.scss`, except for those, that cannot be changed while maintaining the basic design idea.
