### ISSUE TITLE
Make code blocks bigger vertically

### ISSUE THREAD

**Issue by cellio** [codidact/co-design#43]
https://software.codidact.com/questions/278868

Code blocks currently show only about 13 lines before needing to scroll.  I don't know what a reasonable default is, but I agree this is a little small for being able to do code reviews.

The easiest thing to do would be to change the baked-in size to a larger one, but this might cause problems on smaller devices.  I say "might" because you would have to scroll to see the code either way; what the smaller size buys a phone user is being able to skip past the code to see what the actual question is before looking in more detail.  I don't know how many people do code reviews on phones, so I don't know how much of a concern this is.

Not as easy but more friendly would be to use the smaller height *but* provide an "expand" control in the UI -- and, if someone clicks it, prompt for "always expand?" and set that value in a cookie.  I'm saying cookie not user preference because it should be tied to the device; the same user will want different settings on a desktop computer and on a tablet or phone.

The "expand" option I've described could either be a toggle to a (single, baked-in) larger size, or we could allow the user to type in a number of lines (and maybe we pre-fill something larger, like 25).

I'm requesting a complexity assessment on the "expand" option, with or without the user-customized line count.

**Comment by ArtOfCode-** [comment]
Transferred after investigation. The stylesheet that's restricting the code block size is from CD.

**Comment by luap42** [comment]
That’s correct. The relevant line is https://github.com/codidact/co-design/blob/develop/src/common/_config.scss#L92.

**Comment by cellio** [comment]
That's where it's set, so we can change the hard-wired number (and maybe should while we consider other options).  Would making it user-settable also be CoDesign, or QPixel?

**Comment by ArtOfCode-** [comment]
That'd be QPixel, but that's unnecessary complexity for something this simple - the current value is small, but we can change the hard-wired number to something that works well cross-platform.

**Comment by sau226** [comment]
Is there any way I can take this issue? It would just be a simple number change for the line mentioned by luap (inline code embed below): https://github.com/codidact/co-design/blob/76d5a0e55e25d115964aea123a33e5d269231d50/src/common/_config.scss#L92 but I don't want to step on anyone's toes by making the change.

What kind of value would be acceptable here? This is the **total** height. The number of lines **actually shown** is `total height <divided by> 1.5`, owing to an entry in `_typography.scss`: https://github.com/codidact/co-design/blob/76d5a0e55e25d115964aea123a33e5d269231d50/src/common/_typography.scss#L42-43 and as per an answer on a meta category post: https://software.codidact.com/posts/278868/278874#answer-278874. So **we would need to bump it up to 45 in order to actually show 20 lines**, or adjust the line height and this value proportionally to values that show enough lines and have enough height.

Note that after we make this change in the `develop` branch, we would need to **release it on NPM**. Then we would need to go ahead and **bump the stylesheet versions** (https://github.com/codidact/qpixel/blob/develop/app/views/layouts/_head.html.erb#L22, and line 34 of the same file) and **do a prod deploy** to push this live. Ideally we visit the relevant JS files manually just so the CDN fetches it and stores it in its cache before we roll this out to users.

**Comment by cellio** [comment]
@sau226 and there are issues for this in two repos (see links farther up the page), for extra fun.  Yes, this needs to get changed in co-design and then pulled into qpixel.  I'm happy to have you shepherd this through, thanks!  And thanks for testing my PR.

**Comment by sau226** [comment]
@cellio This is now done - just needs a new co-design release and bumping versions of CSS that we then deploy to prod.

Can we close out this iteration of the issue?

**Comment by cellio** [comment]
Closing the co-design issue, though we still need a new release/version bump so it can be imported by qpixel.

**Comment by cellio** [comment]
@ArtOfCode-  please see previous comment.  Thanks.

**Comment by cellio** [comment]
@ArtOfCode- or @luap42 , can one of you do the release-propagation stuff to get this pushed from co-design to qpixel to prod?  Thanks.
