### ISSUE TITLE
Push new version to fix drop-down problem

### ISSUE THREAD

**Issue by cellio** [codidact/co-design#80]
If I understand correctly, https://github.com/codidact/co-design/commit/ffcf9d045f403836b665390b8629d9235fe4255a fixes the problem where you can't click on the inbox notification image or number itself, but if you know to click in the whitespace around it you can see your pending items.  That is frustrating for those who know the workaround and confusing for those who don't.  It's fixed here, I think, but we need a version push from here followed by an import into qpixel for it to get into production.

**Comment by trichoplax** [comment]
Thanks for pushing towards getting this into production.

Maybe part of the problem was that #72 was closed as fixed by #73 even though there hadn't been a release so the fix was only in the code, not in the real world behaviour.

Should we have a policy of only closing bugs when their fix is deployed/released, rather than closing them when their fix is merged into the `develop` branch? Not sure where this would be recorded.

**Comment by trichoplax** [comment]
Is there a known list of people who have access to push a new version of Co-Design to npm and the CDN? If so, would it be helpful to have a team/group for just those people, so issues like this one can be assigned to that team/group?

**Comment by cellio** [comment]
That's a great idea.  @ArtOfCode- , can we create a GH team consisting of the people who can do npm stuff from co-design?

**Comment by cellio** [comment]
Resolved by https://github.com/codidact/co-design/pull/83 .
